name: Auto Assign Issue
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to user
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['devpedrobarbosa']
            })